<?php

namespace App\Controller\Admin;

use App\Entity\Enseignant;
use App\Entity\Utilisateur;
use App\Factory\UtilisateurFactory;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Bridge\Doctrine\DependencyInjection\Security\UserProvider\EntityFactory;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Twig\Node\Expression\VariadicExpression;

class EnseignantCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Enseignant::class;
    }
    private UserPasswordHasherInterface $hasher;

    public function __construct(UserPasswordHasherInterface $hasher)
    {
        $this->hasher = $hasher;
    }

    public function configureFields(string $pageName): iterable
    {
        return [
     TextField::new('numEn')->setLabel('Numero'),
     TextField::new('nomEn')->setLabel('Nom'),
     TextField::new('pnomEn')->setLabel('Prénom'),
            DateField::new('dtnsEn')->setLabel('Date de naissance'),
     TextField::new('adEn')->setLabel("Adresse"),
     TextField::new('cpEn')->setLabel("Code postal"),
     TextField::new('villeEn')->setLabel('Ville'),
     AssociationField::new('cdUtil')->formatValue(function ($value, $entity) {
         return $entity->getCdUtil()->getLogin();
     })->setLabel('Login')->hideOnForm(),
            BooleanField::new('isAdmin')->setLabel('Administrateur')

 ];
    }
    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $this->setUser($entityInstance);
        parent::updateEntity($entityManager, $entityInstance);
    }
    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $this->setUser($entityInstance);
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    /**
     * @param $entityInstance
     * @return void
     */
    public function setUser($entityInstance): void
    {
        $user=$entityInstance->getCdUtil();
        if ($user==null) {
            $lastname = $_POST['Enseignant']['nomEn'];
            $login = strtolower(str_replace(" ", "", "$lastname" . rand(1, 300)));
            $user = new Utilisateur();
            $user->setLogin($login);
            $user->setEmail('default@example.com');
            $user->setPassword($this->hasher->hashPassword($user, $_POST['Enseignant']['dtnsEn']));
            $entityInstance->setCdUtil($user);
        }
        $user->setRoles(['ROLE_ENSEIGNANT']);
        if (array_key_exists('isAdmin', $_POST['Enseignant'])) {
            $user->setRoles(['ROLE_ADMIN,ROLE_ENSEIGNANT']);
        }
        $entityInstance->setFirstConnection(true);
    }
}
