<?php

namespace App\Controller\Admin;

use App\Entity\Enseignant;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class EnseignantCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Enseignant::class;
    }

    public function configureFields(string $pageName): iterable
    {
        return [
     TextField::new('numEn')->setLabel('Numero'),
     TextField::new('nomEn')->setLabel('Nom'),
     TextField::new('pnomEn')->setLabel('Prénom'),
            DateField::new('dtnsEn')->setLabel('Date de naissance'),
     TextField::new('adEn')->setLabel("Adresse"),
     TextField::new('cpEn')->setLabel("Code postal"),
     TextField::new('villeEn')->setLabel('Ville'),
     AssociationField::new('cdUtil')->setFormTypeOptions(['choice_label'=>'login','query_builder'=>function (EntityRepository $entityRepository) {
         return $entityRepository->createQueryBuilder('c')->orderBy('c.login', 'ASC');
     }])->formatValue(function ($value, $entity) {
         return $entity->getCdUtil()->getLogin();
     })->setLabel('login')->hideOnForm(),
            AssociationField::new('cdUtil')->setFormTypeOptions(['choice_label'=>'roles[0]','query_builder'=>function (EntityRepository $entityRepository) {;
            }])->formatValue(function ($value, $entity) {
                $roles=$entity->getCdUtil()->getRoles();
                if ($roles[0]==='ROLE_ENSEIGNANT') {
                    return "<span class='material-icons'>person</span>";
                }
                else{
                    return "<span class='material-icons'>manage_accounts</span>";
                }
            })->setLabel('Roles')
 ];
    }
    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        parent::updateEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }
}
